### ISSUE TITLE
Dashboard Form's Minor Font Changes 

### ISSUE THREAD

**Issue by BhosalePriyanka** [spirit-of-christmas/spectrum#106]
Dashboard Form's Minor Font Changes

**Comment by BhosalePriyanka** [comment]
<img width="1371" alt="Form1" src="https://github.com/spirit-of-christmas/spectrum/assets/52287282/b3919075-0bee-4055-8f3a-ee4a4ac31778">

May I know location of this form?

**Comment by nmunro** [comment]
I'm not seeing this on the staging server, but the template for this is located at:

info/templates/info/dashboard_org.html

It just uses django crispy forms to render the form as is... not sure why phone number appears larger than it should be.

**Comment by BhosalePriyanka** [comment]
Okay let me check code. I only see this form but html lable tag i dont see here.

<form method="POST" class="col-lg-8 col-xl-8 col-md-8 col-sm-12  mx-auto border shadow p-5 m-5 text-center 
fw-bold text-uppercase" action="{% url 'info:dashboard_org' org.slug %}">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-primary" value="Save"/>
  <a href="{% url 'info:dashboard' %}" class="btn btn-danger">Cancel</a>
</form>

**Comment by nmunro** [comment]
`<h2>{{ org.name }}</h2>
<form method="POST" action="{% url 'info:dashboard_org' org.slug %}">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-primary" value="Save"/>
  <a href="{% url 'info:dashboard' %}" class="btn btn-danger">Cancel</a>
</form>
`

The line `{{ form|crispy }}` renders the `OrgForm` (located inside `info/forms.py`) using the package django-crispy-forms (a way to render forms with bootstrap styling) which you can read about here: https://github.com/django-crispy-forms/django-crispy-forms

**Comment by BhosalePriyanka** [comment]
so i dont know python, i'm not able to solve it.,if you are not seeing it at staging ,then we can leave it. if you are okay?

**Comment by nmunro** [comment]
Yeah, we'll close it for now and if it shows up again we'll fix it.
