### ISSUE TITLE
Scheduler 2.0

### ISSUE THREAD

**Issue by nmunro** [spirit-of-christmas/spectrum#118]
Improve the scheduler, this will include:

Tasks:

* [x] Add a field on organisations to "enable schedules"
* [x] Add a section in the dashboard to create a schedule, edit, updated, & delete, this will not be shown if schedules are disabled.
* [x] Edit the event form to show schedules.
* [x] Update scheduler command to only reschedule an event if the org has enabled the schedule.
* [x] Develop a guide/policy for scheduling events.

Notes:

https://freetools.textmagic.com/rrule-generator

The schedule may have been skipped because the foreign key links from the event to the scheduler might not have been saved.

Django depends on [`dateutil`](https://dateutil.readthedocs.io/en/stable/index.html)

```
>>> import dateutil
>>> dateutil.rrule.rrule(freq=dateutil.rrule.MONTHLY, count=4, bysetpos=3, byweekday=5)
<dateutil.rrule.rrule object at 0x7fcae77b3a70>
>>> dateutil.rrule.rrule(freq=dateutil.rrule.MONTHLY, count=4, bysetpos=3, byweekday=5)
<dateutil.rrule.rrule object at 0x7fcae4f144d0>
>>> list(_)
[datetime.datetime(2024, 5, 18, 22, 53, 16), datetime.datetime(2024, 6, 15, 22, 53, 16), datetime.datetime(2024, 7, 20, 22, 53, 16), datetime.datetime(2024, 8, 17, 22, 53, 16)]
```

**Comment by BhosalePriyanka** [comment]
<img width="1168" alt="Scheduler" src="https://github.com/spirit-of-christmas/spectrum/assets/52287282/5651e7d2-a3d2-4908-bb8f-5abf8ffcee89">

Are you expecting page like this ?

**Comment by nmunro** [comment]
As previously discussed, we need to look at implementing an rrule tool (as linked to in the ticket).

The interface must replicate that tool as a schedule is MUCH more complicated than just start and end times. It's frequency, which is a complex thing already solved by ical rrule format.

**Comment by BhosalePriyanka** [comment]
Hi Neil, I dont know much about rrule, I am not able to give my input on this issue. 
Please let me know whcih is other issue should i pick now for my working.
