### ISSUE TITLE
Add a "volunteer with this organisation" feature

### ISSUE THREAD

**Issue by nmunro** [spirit-of-christmas/spectrum#131]
Add a "volunteer with this charity" feature, when browsing through events and resources, add a link that will allow a user to register an interest in helping the organisation, it'll need a basic contact form and to mail the organisation.

Add a "accepting volunteers" check options for organisations so they can allow people to volunteer.

**Comment by BhosalePriyanka** [comment]
Hello Neil,

So for example, here on this resource page we are expedting link, on click it should connect to form.
Is it?
<img width="1422" alt="RESOURCE" src="https://github.com/spirit-of-christmas/spectrum/assets/52287282/4889cde5-54c0-4048-a501-cd03e3bd2505">

**Comment by nmunro** [comment]
I intend to add a flag to the organization model that will allow people to mark the organization as “looking for volunteers”

It will be that flag (a checkbox) that will be checked

So in your opinion where best do you think it should go in the UI?

**Comment by BhosalePriyanka** [comment]
<img width="1417" alt="Main" src="https://github.com/spirit-of-christmas/spectrum/assets/52287282/f56ef02b-5331-4f39-9010-e1b2d9e99079">


As per my view on main page we can add that.

**Comment by nmunro** [comment]
Can you highlight the difference you are proposing as I don't know what I'm looking at besides the index page?

**Comment by BhosalePriyanka** [comment]
On  main page above footer we can create button Looking for Volunteer on click we can add link for form to submit.

**Comment by BhosalePriyanka** [comment]
<img width="1427" alt="ORG" src="https://github.com/spirit-of-christmas/spectrum/assets/52287282/f676c674-6bda-44b1-91f8-9d110bc175d1">


For example, on this page down below facebook link.

**Comment by nmunro** [comment]
Yes I think there is the best place to put it, if you want to put together the basic templating and UI, I can then add the back end model property and connect it up.

**Comment by BhosalePriyanka** [comment]
1. Oaky sure, Let me do form and will let you know.

**Comment by BhosalePriyanka** [comment]
<img width="1417" alt="Volunteer" src="https://github.com/spirit-of-christmas/spectrum/assets/52287282/25b2ad2a-6490-4327-a566-92ac456a9f40">
Hi Neil,

Please have a look and give your suggestion

**Comment by nmunro** [comment]
I like the way that looks, will it open a link using the mailto: prefix with a default title etc?

**Comment by BhosalePriyanka** [comment]
We are link to form right.. why it shoud have " mailto:" ? url of form should be there.

**Comment by nmunro** [comment]
I did say it might connect to a contact form... id have to build the backend form for you to connect to. 

We can do it that way, but id have to implement the form in the `forms.py` file.

If you design the contact form, I can implement it.

The alternative is to just use mailto

**Comment by BhosalePriyanka** [comment]
I can design contact form in html. I am not able to do it in python.
should i create form.html file? 
Name , Email id, Message Is that much field enough for form ?

**Comment by nmunro** [comment]
If you sketch out what form elements you need (name, email etc) I can build the form. A html form in Django is often done using python code (as it can derive from models and do many things in the back end like actually send emails etc) so if you propose a design, I can build the form and make it available to you

**Comment by BhosalePriyanka** [comment]
Please see form
![Uploading Form.png…]()
