### ISSUE TITLE
Collapse sidebar in dashboard on smaller screens

### ISSUE THREAD

**Issue by nmunro** [spirit-of-christmas/spectrum#73]
As per the examples in the bootstrap documentation [here](https://getbootstrap.com/docs/5.0/examples/sidebars/), on a smaller screen device (such as a phone or tablet) the sidebar should be collapsed to show only icons on the left.

**Comment by nmunro** [comment]
So the icons on the left in the full size dashboard have become center aligned, when they should be left aligned. Is it possible to keep them left aligned when the dashboard is full sized?

Otherwise with them at the top, it works well, but the icon placement looks a bit off on "contacts" is it possible the alignment is different?

**Comment by BhosalePriyanka** [comment]
Please check
<img width="1410" alt="page new" src="https://github.com/spirit-of-christmas/spectrum/assets/52287282/c2d9bb44-8df4-4ed3-8826-df8899bdb46f">

**Comment by BhosalePriyanka** [comment]
tested and completed
