### ISSUE TITLE
Add quick filters to search results

### ISSUE THREAD

**Issue by nmunro** [spirit-of-christmas/spectrum#75]
Like any search engine, provide quick filters for specific kinds of results.

<img width="818" alt="Screenshot 2024-03-15 at 23 37 57" src="https://github.com/spirit-of-christmas/spectrum/assets/2406326/097ac31a-910a-488d-a2fc-2dd25a403deb">

We will need an 

* All | * Events | * Resources

Kinda layout using radio buttons or something.

**Comment by nmunro** [comment]
Let's explore that, maybe a drop down with the three options as well. Or maybe a combination of both? A drop down may be more useful on phones where horizontal space is limited?

**Comment by BhosalePriyanka** [comment]
i can make responsive for mobile.Drop down not that much look good.

**Comment by nmunro** [comment]
In what way don't they look good?

**Comment by BhosalePriyanka** [comment]
If you are looking for dropdown then i can do like that, but earlier you said radio button so it will go horiztonatal , i can make it responsive for mobile screen and in case dropdown we cant use icons and redio button.

Please let me know how should i make it?
